[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0x3ddbd9"
index = 16

[[colors.indexed_colors]]
color = "0xff7eb6"
index = 17

[colors.bright]
black = "0x484848"
blue = "0x8cb6ff"
cyan = "0x52bdff"
green = "0x46c880"
magenta = "0xc8a5ff"
red = "0xf16da6"
white = "0xe4e4e5"
yellow = "0x2dc7c4"

[colors.normal]
black = "0x282828"
blue = "0x78a9ff"
cyan = "0x33b1ff"
green = "0x25be6a"
magenta = "0xbe95ff"
red = "0xee5396"
white = "0xdfdfe0"
yellow = "0x08bdba"

[colors.primary]
background = "0x161616"
foreground = "0xf2f4f8"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 5

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bt"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BW"
key = "W"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001Bp"
key = "P"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Be"
key = "E"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BX"
key = "X"
mods = "Alt|Shift"

#[[scheme.indexed_colors]]
#color = "0x3ddbd9"
#index = 16
#
#[[scheme.indexed_colors]]
#color = "0xff7eb6"
#index = 17
#
#[scheme.bright]
#black = "0x484848"
#blue = "0x8cb6ff"
#cyan = "0x52bdff"
#green = "0x46c880"
#magenta = "0xc8a5ff"
#red = "0xf16da6"
#white = "0xe4e4e5"
#yellow = "0x2dc7c4"
#
#[scheme.normal]
#black = "0x282828"
#blue = "0x78a9ff"
#cyan = "0x33b1ff"
#green = "0x25be6a"
#magenta = "0xbe95ff"
#red = "0xee5396"
#white = "0xdfdfe0"
#yellow = "0x08bdba"
#
#[scheme.primary]
#background = "0x161616"
#foreground = "0xf2f4f8"

[scrolling]
history = 50000
multiplier = 3

[window]
decorations = "none"
dynamic_padding = false
dynamic_title = true
opacity = 0.8

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0

[shell]
program = "/bin/zsh"
args = [ "-l", "-c", "tmux" ]
